### ISSUE TITLE
Datasets without information leakage.

### ISSUE THREAD

**Issue by iamxpy** [uta-smile/RetroXpert#14]
Are the three datasets under folder `data/USPTO50K/canonicalized_csv`  already processed by `canonicalize_products.py`? Thanks.

**Comment by chaoyan1037** [comment]
Yes, they are processed under branch canonical_product. You can find them from this path:

https://github.com/uta-smile/RetroXpert/tree/canonical_product/data/USPTO50K/canonicalized_csv

**Comment by iamxpy** [comment]
Thanks.
