### ISSUE TITLE
Input feature channels

### ISSUE THREAD

**Issue by gaozhangyang** [uta-smile/RetroXpert#16]
Thanks for your excellent work! When reproducing your results, I meet some problems and need your help:

**Q1: Why is the actual number of templates different from the paper?**
As for the EGAT model, there are 704(47+657) input node features in the official code,  where 657 may be the dimension of  `patten_feat.` However, I just got `patten_feat` with 529 dimensions after extracting semi-template patterns following the official instructions. 

```python
  # extract semi-tempaltes for training data
  python extract_semi_template_pattern.py --extract_pattern
  
  # find semi-template patterns for all data
  python extract_semi_template_pattern.py
```

Therefore, the number of input feature channels is 576(47+529). Is there something I missed? Or has the author updated the code, making it different from the paper?

**Q2: What are the compositions of 657 dimensions?**
According to Appendix.B in your paper, I guess the extra dimensions(beyond the first 47 atom features) is either 645 or 664(645+10). Why are the extra dimensions 647  in the official code? Is it an inadvertent mistake?

**Comment by chaoyan1037** [comment]
It is not a big problem. With different versions of Rdkit, the extracted number of semi-templates may vary. You may use you what you get.

You may also refer to this [thread](https://github.com/uta-smile/RetroXpert/issues/5).

**Comment by gaozhangyang** [comment]
Thanks for your help!
