### ISSUE TITLE
Paper Retraction

### ISSUE THREAD

**Issue by dixleya** [uta-smile/RetroXpert#17]
Hi, 
Thank you for your work. 

I saw the updated README, showing that the superior performance in your paper was because of a dataset leakage. Shouldn't that warrant a retraction of the paper, given that the results would have played a good role in the acceptance?

**Comment by chaoyan1037** [comment]
Hi,

Thanks for your interest. The updated results of our method are still the best template-free results at the time of submission. Our proposed method is still novel and effective.
