### ISSUE TITLE
EGAT train.py error, size mismatch problem

### ISSUE THREAD

**Issue by otori-bird** [uta-smile/RetroXpert#2]
All i edited is : In "extract_semi_template_pattern.py": deleting "exit(1)"  to get [”patten_feat“] in the graph.

Then i run the train.py, and got this size mismatch error

Traceback (most recent call last):
  File "train.py", line 322, in <module>
    h_pred, e_pred = GAT_model(g_dgl, x_atom)
  File "/home/disk3/zzp/anaconda3/envs/Retro/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/disk3/zzp/IntelligentDesign/RetroXpert/model/gat.py", line 121, in forward
    h, _ = self.gat[l](g, h, merge='flatten')
  File "/home/disk3/zzp/anaconda3/envs/Retro/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/disk3/zzp/IntelligentDesign/RetroXpert/model/gat.py", line 72, in forward
    outs = list(map(lambda x: x(g, h), self.heads))
  File "/home/disk3/zzp/IntelligentDesign/RetroXpert/model/gat.py", line 72, in <lambda>
    outs = list(map(lambda x: x(g, h), self.heads))
  File "/home/disk3/zzp/anaconda3/envs/Retro/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/disk3/zzp/IntelligentDesign/RetroXpert/model/gat.py", line 45, in forward
    g.ndata['h'] = self.embed_node(h)
  File "/home/disk3/zzp/anaconda3/envs/Retro/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/disk3/zzp/anaconda3/envs/Retro/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/disk3/zzp/anaconda3/envs/Retro/lib/python3.6/site-packages/torch/nn/functional.py", line 1371, in linear
    output = input.matmul(weight.t())
RuntimeError: size mismatch, m1: [809 x 57], m2: [703 x 128] at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:273

my package version are just like requirements.txt told:
python 3.6
torch 1.2.0
dgl-cu10.2  0.4.2

**Comment by chaoyan1037** [comment]
Please keep "exit(1)", and run twice.

**Comment by otori-bird** [comment]
> Please keep "exit(1)", and run twice following the instructions.
> 
> ```
> # extract semi-tempaltes for training data
> python extract_template_pattern.py --extract_pattern
> 
> # find semi-template patterns for all data
> python extract_template_pattern.py
> ```

Oh, at first I thought these two commands were alternative.
i got what your code means. It works well like the notes you wrote in the code now.  Wonderful job!

**Comment by iamxpy** [comment]
> Please keep "exit(1)", and run twice following the instructions.
> 
> ```
> # extract semi-tempaltes for training data
> python extract_template_pattern.py --extract_pattern
> 
> # find semi-template patterns for all data
> python extract_template_pattern.py
> ```

I can't find the `extract_template_pattern.py`. Do you mean `extract_semi_template_pattern.py`?

**Comment by chaoyan1037** [comment]
Yes, it is *extract_semi_template_pattern.py*. Sorry for the typo.

**Comment by iamxpy** [comment]
@chaoyan1037 Hi, I didn't make any change to the code, but I am also facing the same error.
```
Namespace(batch_size=32, dataset='USPTO50K', epochs=80, exp_name='USPTO50K_typed', gat_layers=3, heads=4, hidden_dim=128, in_dim=703, load=False, logdir='logs', lr=0.0005, seed=123, test_on_train=False, test_only=False, typed=True, use_cpu=False, valid_only=False)
Counter({1: 3482, 0: 1415, 2: 102, 9: 1, 17: 1})
Counter({1: 27851, 0: 11296, 2: 849, 3: 4, 4: 4, 10: 2, 7: 1, 13: 1})
Epoch 1:   0%|                                                                                                                                                                   | 0/1251 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 322, in <module>
    h_pred, e_pred = GAT_model(g_dgl, x_atom)
  File "/home/xiepengyu/miniconda3/envs/nips/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xiepengyu/RetroXpert/model/gat.py", line 121, in forward
    h, _ = self.gat[l](g, h, merge='flatten')
  File "/home/xiepengyu/miniconda3/envs/nips/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xiepengyu/RetroXpert/model/gat.py", line 72, in forward
    outs = list(map(lambda x: x(g, h), self.heads))
  File "/home/xiepengyu/RetroXpert/model/gat.py", line 72, in <lambda>
    outs = list(map(lambda x: x(g, h), self.heads))
  File "/home/xiepengyu/miniconda3/envs/nips/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xiepengyu/RetroXpert/model/gat.py", line 45, in forward
    g.ndata['h'] = self.embed_node(h)
  File "/home/xiepengyu/miniconda3/envs/nips/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xiepengyu/miniconda3/envs/nips/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/xiepengyu/miniconda3/envs/nips/lib/python3.6/site-packages/torch/nn/functional.py", line 1372, in linear
    output = input.matmul(weight.t())
RuntimeError: size mismatch, m1: [844 x 704], m2: [703 x 128] at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:290
```

How can I fix this? thx!

**Comment by otori-bird** [comment]
> @chaoyan1037 Hi, I didn't make any change to the code, but I am also facing the same error.
> 
> ```
> Namespace(batch_size=32, dataset='USPTO50K', epochs=80, exp_name='USPTO50K_typed', gat_layers=3, heads=4, hidden_dim=128, in_dim=703, load=False, logdir='logs', lr=0.0005, seed=123, test_on_train=False, test_only=False, typed=True, use_cpu=False, valid_only=False)
> Counter({1: 3482, 0: 1415, 2: 102, 9: 1, 17: 1})
> Counter({1: 27851, 0: 11296, 2: 849, 3: 4, 4: 4, 10: 2, 7: 1, 13: 1})
> Epoch 1:   0%|                                                                                                                                                                   | 0/1251 [00:00<?, ?it/s]
> Traceback (most recent call last):
>   File "train.py", line 322, in <module>
>     h_pred, e_pred = GAT_model(g_dgl, x_atom)
>   File "/home/xiepengyu/miniconda3/envs/nips/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/xiepengyu/RetroXpert/model/gat.py", line 121, in forward
>     h, _ = self.gat[l](g, h, merge='flatten')
>   File "/home/xiepengyu/miniconda3/envs/nips/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/xiepengyu/RetroXpert/model/gat.py", line 72, in forward
>     outs = list(map(lambda x: x(g, h), self.heads))
>   File "/home/xiepengyu/RetroXpert/model/gat.py", line 72, in <lambda>
>     outs = list(map(lambda x: x(g, h), self.heads))
>   File "/home/xiepengyu/miniconda3/envs/nips/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/xiepengyu/RetroXpert/model/gat.py", line 45, in forward
>     g.ndata['h'] = self.embed_node(h)
>   File "/home/xiepengyu/miniconda3/envs/nips/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/xiepengyu/miniconda3/envs/nips/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 87, in forward
>     return F.linear(input, self.weight, self.bias)
>   File "/home/xiepengyu/miniconda3/envs/nips/lib/python3.6/site-packages/torch/nn/functional.py", line 1372, in linear
>     output = input.matmul(weight.t())
> RuntimeError: size mismatch, m1: [844 x 704], m2: [703 x 128] at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:290
> ```
> 
> How can I fix this? thx!

modify the in_dim in "train.py" according to your number of  extracted semi templates.

for example, if you got 655 semi templates, your in_dim should be 47 + 655.

**Comment by iamxpy** [comment]
> > @chaoyan1037 Hi, I didn't make any change to the code, but I am also facing the same error.
> > ```
> > Namespace(batch_size=32, dataset='USPTO50K', epochs=80, exp_name='USPTO50K_typed', gat_layers=3, heads=4, hidden_dim=128, in_dim=703, load=False, logdir='logs', lr=0.0005, seed=123, test_on_train=False, test_only=False, typed=True, use_cpu=False, valid_only=False)
> > Counter({1: 3482, 0: 1415, 2: 102, 9: 1, 17: 1})
> > Counter({1: 27851, 0: 11296, 2: 849, 3: 4, 4: 4, 10: 2, 7: 1, 13: 1})
> > Epoch 1:   0%|                                                                                                                                                                   | 0/1251 [00:00<?, ?it/s]
> > Traceback (most recent call last):
> >   File "train.py", line 322, in <module>
> >     h_pred, e_pred = GAT_model(g_dgl, x_atom)
> >   File "/home/xiepengyu/miniconda3/envs/nips/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
> >     result = self.forward(*input, **kwargs)
> >   File "/home/xiepengyu/RetroXpert/model/gat.py", line 121, in forward
> >     h, _ = self.gat[l](g, h, merge='flatten')
> >   File "/home/xiepengyu/miniconda3/envs/nips/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
> >     result = self.forward(*input, **kwargs)
> >   File "/home/xiepengyu/RetroXpert/model/gat.py", line 72, in forward
> >     outs = list(map(lambda x: x(g, h), self.heads))
> >   File "/home/xiepengyu/RetroXpert/model/gat.py", line 72, in <lambda>
> >     outs = list(map(lambda x: x(g, h), self.heads))
> >   File "/home/xiepengyu/miniconda3/envs/nips/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
> >     result = self.forward(*input, **kwargs)
> >   File "/home/xiepengyu/RetroXpert/model/gat.py", line 45, in forward
> >     g.ndata['h'] = self.embed_node(h)
> >   File "/home/xiepengyu/miniconda3/envs/nips/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
> >     result = self.forward(*input, **kwargs)
> >   File "/home/xiepengyu/miniconda3/envs/nips/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 87, in forward
> >     return F.linear(input, self.weight, self.bias)
> >   File "/home/xiepengyu/miniconda3/envs/nips/lib/python3.6/site-packages/torch/nn/functional.py", line 1372, in linear
> >     output = input.matmul(weight.t())
> > RuntimeError: size mismatch, m1: [844 x 704], m2: [703 x 128] at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:290
> > ```
> > 
> > 
> > How can I fix this? thx!
> 
> modify the in_dim in "train.py" according to your number of extracted semi templates.
> 
> for example, if you got 655 semi templates, your in_dim should be 47 + 655.

Thanks, it works.
