### ISSUE TITLE
Script to generate canonicalized_csv files

### ISSUE THREAD

**Issue by linminhtoo** [uta-smile/RetroXpert#3]
Hi Chaochao and team,

Excellent work on RetroXpert! I want to train the model on my own processed version of USPTO-50k dataset (I download the 3 files from schneider50k folder and remove certain reactions for my own project, e.g. duplicates, same rxn_smi that occur in both train & test) https://www.dropbox.com/sh/6ideflxcakrak10/AADTbFBC0F8ax55-z-EDgrIza?dl=0 

However, I am not sure what exactly is involved to get the same kind of 'canonicalized_csv' files. Could you please elaborate on the original source of your USPTO-50k & USPTO_FULL data, and upload the script to generate the canonicalized_csv files from that original data? 

Thank you very much and happy new year.

EDIT: 
I believe this is a trivial step, and use this simple function. Still, would like to confirm with authors for any other preprocessing steps involved. 
```
def canonicalize_rxn_smi(
    rxn_smi: str,
    ):
    prod_smi = rxn_smi.split('>>')[-1]
    prod_smi_canon = Chem.MolToSmiles(Chem.MolFromSmiles(prod_smi), True)
    rcts_smi = rxn_smi.split('>>')[0]
    rcts_smi_canon = Chem.MolToSmiles(Chem.MolFromSmiles(rcts_smi), True)
    return rcts_smi_canon + '>>' + prod_smi_canon
```

**Comment by chaoyan1037** [comment]
Hi,

Here is how we preprocess the product SMILES.

https://github.com/uta-smile/RetroXpert/blob/main/canonicalize_products.py

**Comment by linminhtoo** [comment]
Thanks! If you don't mind, could you briefly explain your logic?

e.g. I don't really understand why you do `product = Chem.MolToSmiles(mol_cano, canonical=False)` in line 30, with canonical=False. 

When I retrain the RGN & EGAT, I just do something like below to canonicalize the rxn_smi to get the input CSV files. It works and I can reproduce the reported accuracies.
```
def canonicalize_rxn_smi(
    rxn_smi: str,
    ):
    prod_smi = rxn_smi.split('>>')[-1]
    prod_smi_canon = Chem.MolToSmiles(Chem.MolFromSmiles(prod_smi), True)
    rcts_smi = rxn_smi.split('>>')[0]
    rcts_smi_canon = Chem.MolToSmiles(Chem.MolFromSmiles(rcts_smi), True)
    return rcts_smi_canon + '>>' + prod_smi_canon
```

**Comment by chaoyan1037** [comment]
We have an important update of our method. Please refer to the readme for more details.
