### ISSUE TITLE
How to use canonicalize_products.py

### ISSUE THREAD

**Issue by iamxpy** [uta-smile/RetroXpert#7]
I found out that files under `USPTO50K/canonicalized_csv/` are not the same as the files provided by [GLN](https://github.com/Hanjun-Dai/GLN), and I thought maybe the only difference is the products in your files are canonicalized, so I used `canonicalize_products.py` to process the files from GLN. Let's say the processed training file is `processed_train.csv`, and I used the following snippet to compare the smiles between these file:

```python
train=pd.read_csv('USPTO50K/canonicalized_csv/train.csv')
train2=pd.read_csv('processed_train.csv')
t=train['rxn_smiles']==train2['rxn_smiles']
print(np.all(np.array(t.tolist())))
```

The last statement prints a `False`, which is not as expected. What am I missing? Thanks!

**Comment by chaoyan1037** [comment]
I guess it is supposed to be the same if the dataset splits are the same. You may look into the details and find out the difference.

**Comment by iamxpy** [comment]
> I guess it is supposed to be the same if the dataset splits are the same. You may look into the details and find out the difference.

The data splits are exactly the same, because they have the same `id` column. And there are 669 samples that have different reaction SMILES in `train` and `train2`. For example, for the 50th sample, the reaction SMILES after processed by `canonicalize_products.py` is: 
```py
'[CH3:1][C:2]1([CH3:3])[C@:4]2([C:5](=[O:6])[NH:7][c:8]3[cH:9][cH:10][c:11]([Cl:12])[cH:13][c:14]3[C:15](=[O:16])[C:17]([F:18])([F:19])[F:20])[CH2:21][CH2:22][C@@:23]1([CH3:24])[C:25](=[O:26])[O:27]2.[CH:28]#[C:29][CH:30]1[CH2:31][CH2:32]1>>[CH3:1][C:2]1([CH3:3])[C@@:23]2([CH3:24])[CH2:22][CH2:21][C@:4]1([C:5](=[O:6])[NH:7][c:8]1[cH:9][cH:10][c:11]([Cl:12])[cH:13][c:14]1[C@@:15]([OH:16])([C:28]#[C:29][CH:30]1[CH2:31][CH2:32]1)[C:17]([F:18])([F:19])[F:20])[O:27][C:25]2=[O:26]'
```

However, the reaction SMILES from your training file is:
```sh
'[CH3:1][C:2]1([CH3:3])[C@:4]2([C:5](=[O:6])[NH:7][c:8]3[cH:9][cH:10][c:11]([Cl:12])[cH:13][c:14]3[C:15](=[O:16])[C:17]([F:18])([F:19])[F:20])[CH2:21][CH2:22][C@@:23]1([CH3:24])[C:25](=[O:26])[O:27]2.[CH:28]#[C:29][CH:30]1[CH2:31][CH2:32]1>>[CH3:1][C:2]1([CH3:3])[C@:4]2([C:5](=[O:6])[NH:7][c:8]3[cH:9][cH:10][c:11]([Cl:12])[cH:13][c:14]3[C@@:15]([OH:16])([C:28]#[C:29][CH:30]3[CH2:31][CH2:32]3)[C:17]([F:18])([F:19])[F:20])[CH2:21][CH2:22][C@@:23]1([CH3:24])[C:25](=[O:26])[O:27]2'
```

**Comment by chaoyan1037** [comment]
Which RDkit version do you use? You may check your installed packages. I guess it might to related to these packages.

**Comment by iamxpy** [comment]
> Which RDkit version do you use? You may check your installed packages. I guess it might to related to these packages.

Sorry for not using exact the same version of RDkit, but after I change the RDkit version from `2019.09.3-py36he9dd633_1` to `2019.09.3-py36hb31dc5d_0` following the [requirements.txt](https://github.com/uta-smile/RetroXpert/blob/4fc5a69812a8393ad57daa5abd1f949d5c6a9ffe/requirements.txt#L62), there are still 686 samples that mismatch the corresponding sample in your training files.

```sh
The following packages will be DOWNGRADED:

  boost                               1.72.0-py36h9de70de_0 --> 1.70.0-py36h9de70de_1
  boost-cpp                               1.72.0-h8e57a91_0 --> 1.70.0-h8e57a91_2
  rdkit                            2019.09.3-py36he9dd633_1 --> 2019.09.3-py36hb31dc5d_0
```

```python
In [8]: np.all(train.iloc[:,2]==train2.iloc[:,3])
Out[8]: False
In [10]: t=train.iloc[:,2]==train2.iloc[:,3]

In [11]: for i in range(len(t)):
    ...:     if not t[i]:
    ...:         print(i)
    ...:
50
110
329
396
436
703
733
929
988
1008
...........................
In [12]: np.sum(t)
Out[12]: 39322

In [13]: train.shape
Out[13]: (40008, 3)

In [14]: 40008-39322
Out[14]: 686
```

**Comment by chaoyan1037** [comment]
I am not sure what is going on there. Maybe you can use what you get. It does not matter.

**Comment by iamxpy** [comment]
> I am not sure what is going on there. Maybe you can use what you get. It does not matter.

OK, maybe you are right, at least the data splits are the same, and only 686 of 40008 samples are not exact the same.

**Comment by chaoyan1037** [comment]
We have an important update of our method. Please refer to the readme for more details.
