### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '../../experiments/results/predictions_on_USPTO50K-aug-typed_test-prediction.txt'

### ISSUE THREAD

**Issue by iamxpy** [uta-smile/RetroXpert#8]
After trained the RGN model and averaged the checkpoints, I tried to run `bash translate.sh`, but got the following error,

```sh
(nips) hugy@robotics180:~/RetroXpert/OpenNMT-py/script/USPTO50K-aug-typed$ bash translate.sh
Traceback (most recent call last):
  File "../../onmt/bin/translate.py", line 52, in <module>
    main()
  File "../../onmt/bin/translate.py", line 48, in main
    translate(opt)
  File "../../onmt/bin/translate.py", line 18, in translate
    translator = build_translator(opt, report_score=True)
  File "/home/hugy/miniconda3/envs/nips/lib/python3.6/site-packages/onmt/translate/translator.py", line 24, in build_translator
    out_file = codecs.open(opt.output, 'w+', 'utf-8')
  File "/home/hugy/miniconda3/envs/nips/lib/python3.6/codecs.py", line 895, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: '../../experiments/results/predictions_on_USPTO50K-aug-typed_test-prediction.txt'
```
Where can we get the file `predictions_on_USPTO50K-aug-typed_test-prediction.txt`?

**Comment by chaoyan1037** [comment]
Please follow the instructions in README carefully. 
```
# Generate synthons for test data according to the bond disconnection prediction in step-1, to do 2-step direct prediction:
python prepare_test_prediction.py  --typed

```

**Comment by iamxpy** [comment]
> Please follow the instructions in README carefully.
> 
> ```
> # Generate synthons for test data according to the bond disconnection prediction in step-1, to do 2-step direct prediction:
> python prepare_test_prediction.py  --typed
> ```

I have already run the script `python prepare_test_prediction.py --typed` and also checked the code in the python file, it seems like it only generates the file [src-test-prediction.txt](https://github.com/uta-smile/RetroXpert/blob/4fc5a69812a8393ad57daa5abd1f949d5c6a9ffe/prepare_test_prediction.py#L149) instead of `predictions_on_USPTO50K-aug-typed_test-prediction.txt`.

**Comment by linminhtoo** [comment]
> > Please follow the instructions in README carefully.
> > ```
> > # Generate synthons for test data according to the bond disconnection prediction in step-1, to do 2-step direct prediction:
> > python prepare_test_prediction.py  --typed
> > ```
> 
> I have already run the command `python prepare_test_prediction.py --typed` and also checked the code in the python file, it seems like it only generates the file [src-test-prediction.txt](https://github.com/uta-smile/RetroXpert/blob/4fc5a69812a8393ad57daa5abd1f949d5c6a9ffe/prepare_test_prediction.py#L149) instead of `predictions_on_USPTO50K-aug-typed_test-prediction.txt`.

Not sure what's the problem in your case. You are right that prepare_test_prediction.py outputs the src-test-prediction.txt; basically the script takes the bond disconnection predictions from EGAT & generates synthons & smi tokenizes them. 

I ran translate.sh & also inspected the code in detail. I am sure it outputs the `predictions_on_USPTO50K-aug-typed_test-prediction.txt` file. It will be in `OpenNMT-py/experiments/results/ folder`.

**Comment by iamxpy** [comment]
> I ran translate.sh & also inspected the code in detail. I am sure it outputs the predictions_on_USPTO50K-aug-typed_test-prediction.txt file. It will be in OpenNMT-py/experiments/results/ folder.

Did you mean the script `translate.sh` or `translate.py` outputs the file `predictions_on_USPTO50K-aug-typed_test-prediction.txt`? I encountered the `FileNotFoundError` when I ran the script `translate.sh`, not after that.

**Comment by chaoyan1037** [comment]
> > > Please follow the instructions in README carefully.
> > > ```
> > > # Generate synthons for test data according to the bond disconnection prediction in step-1, to do 2-step direct prediction:
> > > python prepare_test_prediction.py  --typed
> > > ```
> > 
> > 
> > I have already run the command `python prepare_test_prediction.py --typed` and also checked the code in the python file, it seems like it only generates the file [src-test-prediction.txt](https://github.com/uta-smile/RetroXpert/blob/4fc5a69812a8393ad57daa5abd1f949d5c6a9ffe/prepare_test_prediction.py#L149) instead of `predictions_on_USPTO50K-aug-typed_test-prediction.txt`.
> 
> Not sure what's the problem in your case. You are right that `prepare_test_prediction.py `outputs the `src-test-prediction.txt`; basically the script takes the bond disconnection predictions from EGAT & generates synthons & smi tokenizes them. This file will be in `OpenNMT-py/data/USPTO50K-aug-typed/` folder
> 
> I ran `translate.sh` & also inspected the code in detail. I am sure it outputs the `predictions_on_USPTO50K-aug-typed_test-prediction.txt` file. It will be in `OpenNMT-py/experiments/results/` folder.

You are right. That file is generated by *translate.sh*.

**Comment by chaoyan1037** [comment]
> > I ran translate.sh & also inspected the code in detail. I am sure it outputs the predictions_on_USPTO50K-aug-typed_test-prediction.txt file. It will be in OpenNMT-py/experiments/results/ folder.
> 
> Did you mean the script `translate.sh` or `translate.py` outputs the file `predictions_on_USPTO50K-aug-typed_test-prediction.txt`? I encountered the `FileNotFoundError` when I ran the script `translate.sh`, not after that.

Your error info indicates "FileNotFoundError: [Errno 2] No such file or directory: '../../experiments/results/", I guess you do not have the directory "experiments/results/". You may create a "experiments/results/" filefolder.

**Comment by iamxpy** [comment]
> > > I ran translate.sh & also inspected the code in detail. I am sure it outputs the predictions_on_USPTO50K-aug-typed_test-prediction.txt file. It will be in OpenNMT-py/experiments/results/ folder.
> > 
> > 
> > Did you mean the script `translate.sh` or `translate.py` outputs the file `predictions_on_USPTO50K-aug-typed_test-prediction.txt`? I encountered the `FileNotFoundError` when I ran the script `translate.sh`, not after that.
> 
> Your error info indicates "FileNotFoundError: [Errno 2] No such file or directory: '../../experiments/results/", I guess you do not have the directory "experiments/results/". You may create a "experiments/results/" filefolder.

It works, thanks for your time.
